services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev

  krakend:
    image: devopsfaith/krakend:2.2
    container_name: gateway
    ports:
      - "8081:8080"
    expose:
      - 8081
    volumes:
      - ./config/krakend:/etc/krakend

  microservice1:
    build: ./microservice1
    container_name: microservice1
    ports:
      - 3000:3000
  microservice2:
    build: ./microservice2
    container_name: microservice2
    ports:
      - 3001:3001
