services:
  traefik:
    image: traefik:v2.10.4
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      # Traefik mit der Zeit vom Server syncronisieren
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/log/traefik/:/logs/
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.services.traefik.loadbalancer.server.port=8081"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,DELETE,POST"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworigin=*"
      - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.testheader.headers.addvaryheader=true"
    
    networks:
      - proxy

  krakend:
    image: devopsfaith/krakend:watch
    container_name: gateway
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    volumes:
      - ./config/krakend:/etc/krakend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=PathPrefix(`/api/`)"
      - "traefik.http.routers.gateway.service=gateway"
      - "traefik.http.services.gateway.loadbalancer.server.port=9901"
      - "traefik.http.middlewares.gateway.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.gateway.stripprefix.forceSlash=false"
      - "traefik.http.routers.gateway.middlewares=gateway"
    networks:
      - proxy

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_HOSTNAME_STRICT=false
    command: start-dev
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.keycloak-header.headers.customrequestheaders.X-Forwarded-For=keycloak.localhost"
      - "traefik.http.middlewares.keycloak-header.headers.customrequestheaders.X-Forwarded-Proto=http"
      - "traefik.http.middlewares.keycloak-header.headers.customrequestheaders.X-Forwarded-Port=8080"
    networks:
      - proxy

  microservice1:
    build: ./microservice1
    container_name: microservice1
    ports:
      - 3000:3000
  microservice2:
    build: ./microservice2
    container_name: microservice2
    ports:
      - 3001:3001

networks:
  proxy:
    name: proxy
    external: true
    driver: bridge
    attachable: true